SELECT A, SUM(B) AS sb
FROM (SELECT DISTINCT A, B FROM NIKOVITS.R)
GROUP BY A;

SELECT B, SUM(D) as sm 
FROM NIKOVITS.R NATURAL JOIN NIKOVITS.S 
GROUP BY B
HAVING AVG(D) < 13 AND SUM(D) < 50
ORDER BY sm;

SELECT NIKOVITS.R.C, SUM(B) as sb 
FROM NIKOVITS.R, (SELECT DISTINCT C FROM NIKOVITS.S) S
WHERE NIKOVITS.R.C = S.C
GROUP BY NIKOVITS.R.C;

SELECT dnev 
FROM NIKOVITS.DOLGOZO
WHERE dkod 
IN (
    SELECT DISTINCT D1.fonoke
    FROM NIKOVITS.DOLGOZO D1
    JOIN NIKOVITS.DOLGOZO D2
    ON D1.fonoke = D2.fonoke 
    AND EXTRACT(YEAR FROM D1.belepes) != EXTRACT(YEAR FROM D2.belepes)
);

SELECT also, felso 
FROM NIKOVITS.FIZ_KATEGORIA
WHERE kategoria 
IN (
    SELECT kategoria
    FROM NIKOVITS.DOLGOZO
    JOIN NIKOVITS.FIZ_KATEGORIA 
    ON fizetes BETWEEN also AND felso
    GROUP BY kategoria
    HAVING COUNT(DISTINCT foglalkozas) = 1
);

CREATE TABLE DOLGOZO2 AS 
SELECT * FROM NIKOVITS.DOLGOZO;

UPDATE DOLGOZO2
SET fizetes = fizetes + (
    SELECT FONOK.fizetes / 2 
    FROM DOLGOZO2 FONOK
    WHERE DOLGOZO2.fonoke = FONOK.dkod
)
WHERE dnev 
IN (
    SELECT dnev
    FROM DOLGOZO2
    WHERE dkod 
    NOT IN (SELECT fonoke FROM DOLGOZO2 WHERE fonoke IS NOT NULL)
);

SELECT dnev, fizetes
FROM DOLGOZO2
WHERE dkod NOT IN (SELECT fonoke FROM DOLGOZO2 WHERE fonoke IS NOT NULL);













